export type InfluencerCountry =
  | 'Egypt'
  | 'Saudi Arabia'
  | 'United Arab Emirates'
  | 'Qatar'
  | 'Bahrain'
  | 'Kuwait'
  | 'Oman'
  | 'Regional';

export type InfluencerLane =
  | 'Founder'
  | 'Investor'
  | 'Ecosystem'
  | 'Policy'
  | 'Media & Research';

export type Influencer = {
  name: string;
  country: InfluencerCountry;
  lane: InfluencerLane;
  organisation: string;
  linkedinUrl: string;
  priority: boolean;
  arabicOrBilingual: boolean;
};

export const verifiedAt = '2026-08-28' as const;
export const INFLUENCERS_VERIFIED_AT = verifiedAt;

export const INFLUENCERS: Influencer[] = [
  // Cross-regional research and media
  {
    name: 'Zubair Naeem Paracha',
    country: 'Regional',
    lane: 'Media & Research',
    organisation: 'MENAbytes, Termsheet',
    linkedinUrl: 'https://www.linkedin.com/in/xparacha',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Wesley Schwalje',
    country: 'Regional',
    lane: 'Media & Research',
    organisation: 'Tahseen Consulting',
    linkedinUrl: 'https://www.linkedin.com/in/wesschwalje',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Miram Wafik',
    country: 'Regional',
    lane: 'Media & Research',
    organisation: 'The Associate / Funding Pulse',
    linkedinUrl: 'https://www.linkedin.com/in/miram-wafik-31b093133',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Lisa van Vuuren',
    country: 'Regional',
    lane: 'Media & Research',
    organisation: 'The Start-up Pulse',
    linkedinUrl: 'https://www.linkedin.com/in/lisa-van-vuuren-60785b13',
    priority: false,
    arabicOrBilingual: false,
  },

  // Egypt
  {
    name: 'Mounir Nakhla',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'MNT-Halan',
    linkedinUrl: 'https://www.linkedin.com/in/mounir-nakhla',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Mostafa Kandil',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Swvl',
    linkedinUrl: 'https://www.linkedin.com/in/mostafaeissakandil',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ashraf Sabry',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Fawry',
    linkedinUrl: 'https://www.linkedin.com/in/ashraf-sabry',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Islam Shawky',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Paymob',
    linkedinUrl: 'https://www.linkedin.com/in/islam-shawky-993306265',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mostafa Amin',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Breadfast',
    linkedinUrl: 'https://www.linkedin.com/in/mostafaaminway',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ahmed Wadi',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Money Fellows',
    linkedinUrl: 'https://www.linkedin.com/in/ahmadwadi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mostafa El-Beltagy',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Nawy',
    linkedinUrl: 'https://www.linkedin.com/in/mostafa-el-beltagy-240b8342',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohamed Ezzat',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Bosta',
    linkedinUrl: 'https://www.linkedin.com/in/mohamed-ezzat-67aba7a4',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Omar Saleh',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Khazna',
    linkedinUrl: 'https://www.linkedin.com/in/omar-saleh-7078555',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ahmed Sabbah',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Telda',
    linkedinUrl: 'https://www.linkedin.com/in/ahmedsabbah',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Belal El-Megharbel',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'MaxAB',
    linkedinUrl: 'https://www.linkedin.com/in/belal-el-megharbel-34718023',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Aly Eltayeb',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Shift EV',
    linkedinUrl: 'https://www.linkedin.com/in/alyeltayeb',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Omar Gabr',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Luciq, formerly Instabug',
    linkedinUrl: 'https://www.linkedin.com/in/okgabr',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Omar Shoukry Sakr',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Nawah Scientific',
    linkedinUrl: 'https://www.linkedin.com/in/omar-shoukry-sakr-phd-mba',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Nour Emam',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Daleela',
    linkedinUrl: 'https://www.linkedin.com/in/nourmemam',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Amir Barsoum',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'InVitro Capital; Vezeeta founder',
    linkedinUrl: 'https://www.linkedin.com/in/amirmbarsoum',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Tarek Assaad',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Algebra Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/tassaad',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Karim Hussein',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Algebra Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/karimhussein',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Laila Hassan',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Algebra Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/lailaohassan',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Omar Khashaba',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Algebra Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/okhashaba',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ahmed El Alfi',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Sawari Ventures; Flat6Labs cofounder',
    linkedinUrl: 'https://www.linkedin.com/in/ahmed-el-alfi-622a204b',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Hany Al-Sonbaty',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Sawari Ventures; F6 Group',
    linkedinUrl: 'https://www.linkedin.com/in/hany-al-sonbaty-12274322',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Dina el-Shenoufy',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'F6 Group and F6 Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/dinaelshenoufy',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Ramez El-Serafy',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'F6 Group and F6 Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/ramezm',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohamed El Sayed Okasha',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'DisrupTech Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/mohamed-el-sayed-okasha-056b87a2',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Tarek Fahim',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Endure Capital',
    linkedinUrl: 'https://www.linkedin.com/in/tarekfahim',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Karim Beshara',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'A15',
    linkedinUrl: 'https://www.linkedin.com/in/karimbeshara',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hanan Abdel Meguid',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'Kamelizer',
    linkedinUrl: 'https://www.linkedin.com/in/hmeguid',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Dalia Ibrahim',
    country: 'Egypt',
    lane: 'Investor',
    organisation: 'EdVentures',
    linkedinUrl: 'https://www.linkedin.com/in/daliamohamedibrahim',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohamed Aboulnaga “Nagaty”',
    country: 'Egypt',
    lane: 'Founder',
    organisation: 'Exits MENA; FORAS AI',
    linkedinUrl: 'https://www.linkedin.com/in/nagaty',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Fadi Antaki',
    country: 'Egypt',
    lane: 'Ecosystem',
    organisation: 'BitRoot; formerly A15',
    linkedinUrl: 'https://www.linkedin.com/in/fadiantaki',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdelhameed Sharara',
    country: 'Egypt',
    lane: 'Ecosystem',
    organisation: 'RiseUp',
    linkedinUrl: 'https://www.linkedin.com/in/abdelhameed-sharara-6a983456',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Ayman Ismail',
    country: 'Egypt',
    lane: 'Ecosystem',
    organisation: 'AUC',
    linkedinUrl: 'https://www.linkedin.com/in/aymanism',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Amr El Abd',
    country: 'Egypt',
    lane: 'Ecosystem',
    organisation: 'Endeavor MENA; PM adviser',
    linkedinUrl: 'https://www.linkedin.com/in/amr-elabd79',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Maged Ghoneima',
    country: 'Egypt',
    lane: 'Ecosystem',
    organisation: 'Startup Egypt',
    linkedinUrl: 'https://www.linkedin.com/in/mghoneima',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohamed Ehab Hafez',
    country: 'Egypt',
    lane: 'Media & Research',
    organisation: 'Entlaq',
    linkedinUrl: 'https://www.linkedin.com/in/mohamed-ehab-hafez',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Tamer Taha',
    country: 'Egypt',
    lane: 'Policy',
    organisation: 'Egypt Startup Charter contributor',
    linkedinUrl: 'https://www.linkedin.com/in/tamertaha',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohamed Farid Saleh',
    country: 'Egypt',
    lane: 'Policy',
    organisation: 'Minister of Investment and Foreign Trade',
    linkedinUrl: 'https://www.linkedin.com/in/mohamed-farid-saleh-97527246',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Rania Ayman',
    country: 'Egypt',
    lane: 'Ecosystem',
    organisation: 'Entreprenelle',
    linkedinUrl: 'https://www.linkedin.com/in/raniaayman',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Gamal Helmy',
    country: 'Egypt',
    lane: 'Media & Research',
    organisation: 'WAYA Media',
    linkedinUrl: 'https://www.linkedin.com/in/gamal-helmy',
    priority: false,
    arabicOrBilingual: true,
  },

  // Saudi Arabia
  {
    name: 'Nora M. Alsarhan',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Saudi Venture Capital',
    linkedinUrl: 'https://www.linkedin.com/in/nora-m-alsarhan',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Bandr Alhomaly',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Jada',
    linkedinUrl: 'https://www.linkedin.com/in/bandr-alhomaly-cfa-a0603152',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdulrahman Tarabzouni',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'STV',
    linkedinUrl: 'https://www.linkedin.com/in/aitmit',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Amal Dokhan',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: '500 Global MENA',
    linkedinUrl: 'https://www.linkedin.com/in/amaldokhan',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Omar Almajdouie',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'RAED Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/omaralmajdouie',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdulaziz Al Omran',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Impact46',
    linkedinUrl: 'https://www.linkedin.com/in/abdulaziz-al-omran-82029a2',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdullah Altamami',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Merak Capital',
    linkedinUrl: 'https://www.linkedin.com/in/aaltamami',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Adwa AlDakheel',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Falak Investment Hub',
    linkedinUrl: 'https://www.linkedin.com/in/adwa-aldakheel-ababb23a',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Fahad Alidi',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Wa’ed',
    linkedinUrl: 'https://www.linkedin.com/in/fahadalidi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohammed Almeshekah',
    country: 'Saudi Arabia',
    lane: 'Investor',
    organisation: 'Outliers',
    linkedinUrl: 'https://www.linkedin.com/in/meshekah',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Badr Al Badr',
    country: 'Saudi Arabia',
    lane: 'Ecosystem',
    organisation: 'Misk Foundation',
    linkedinUrl: 'https://www.linkedin.com/in/badralbadr',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ibrahim Neyaz',
    country: 'Saudi Arabia',
    lane: 'Policy',
    organisation: 'NTDP',
    linkedinUrl: 'https://www.linkedin.com/in/alneyazi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Saud Alsabhan',
    country: 'Saudi Arabia',
    lane: 'Ecosystem',
    organisation: 'Monsha’at',
    linkedinUrl: 'https://www.linkedin.com/in/saud-alsabhan-16b1927',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hattan Ahmed',
    country: 'Saudi Arabia',
    lane: 'Ecosystem',
    organisation: 'KAUST and TAQADAM',
    linkedinUrl: 'https://www.linkedin.com/in/hattan-ahmed-2222484',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Tareq Amin',
    country: 'Saudi Arabia',
    lane: 'Ecosystem',
    organisation: 'HUMAIN',
    linkedinUrl: 'https://www.linkedin.com/in/tareq-amin-b58302',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdulmajeed Alsukhan',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Tamara',
    linkedinUrl:
      'https://www.linkedin.com/in/abdulmajeed-alsukhan-%D8%B9%D8%A8%D8%AF%D8%A7%D9%84%D9%85%D8%AC%D9%8A%D8%AF-%D8%A7%D9%84%D8%B5%D9%8A%D8%AE%D8%A7%D9%86-13000a58',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Ahmad AlZaini',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Foodics',
    linkedinUrl: 'https://www.linkedin.com/in/alzaini',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Hisham Al-Falih',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Lean Technologies',
    linkedinUrl: 'https://www.linkedin.com/in/hishamfalih',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdullah Asiri',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Lucidya',
    linkedinUrl: 'https://www.linkedin.com/in/amasiri',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ahmed Hamdan',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Unifonic',
    linkedinUrl: 'https://www.linkedin.com/in/hamdanahmed',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdulaziz Al Jouf',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'PayTabs',
    linkedinUrl: 'https://www.linkedin.com/in/abdulaziz-aljouf',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Nawaf Hareeri',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Salla',
    linkedinUrl: 'https://www.linkedin.com/in/nawaf-hareeri-47b42a152',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Osama AlRaee',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Lendo',
    linkedinUrl: 'https://www.linkedin.com/in/osamaalraee',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Sami Alhelwah',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Nana',
    linkedinUrl: 'https://www.linkedin.com/in/samialhulwah',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohammad Almadani',
    country: 'Saudi Arabia',
    lane: 'Founder',
    organisation: 'Classera',
    linkedinUrl: 'https://www.linkedin.com/in/mohammad-s-almadani-12307b29',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mojahed Akil',
    country: 'Saudi Arabia',
    lane: 'Media & Research',
    organisation: 'Beyond Ventures; Saudi startup newsletter',
    linkedinUrl: 'https://www.linkedin.com/in/mojahedakil',
    priority: false,
    arabicOrBilingual: true,
  },

  // United Arab Emirates
  {
    name: 'Omar Sultan AlOlama',
    country: 'United Arab Emirates',
    lane: 'Policy',
    organisation: 'UAE government; Dubai Chamber',
    linkedinUrl: 'https://www.linkedin.com/in/omar-sultan-alolama-305b8366',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Khalfan Belhoul',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Dubai Future Foundation',
    linkedinUrl: 'https://www.linkedin.com/in/khalfan-belhoul-937a4a1a2',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ahmad Ali Alwan',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Hub71',
    linkedinUrl: 'https://www.linkedin.com/in/ahmad-ali-alwan-64900b18',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Sara Al Nuaimi',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Sheraa',
    linkedinUrl: 'https://www.linkedin.com/in/sara-al-nuaimi-910a882',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Bodour Al Qasimi',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Sheraa',
    linkedinUrl: 'https://www.linkedin.com/in/bodour-al-qasimi-61a79b165',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Badr Al-Olama',
    country: 'United Arab Emirates',
    lane: 'Policy',
    organisation: 'Abu Dhabi Investment Office',
    linkedinUrl: 'https://www.linkedin.com/in/badr-al-olama-828816',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hadi Badri',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Dubai Founders HQ',
    linkedinUrl: 'https://www.linkedin.com/in/hadibadri',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Arif Amiri',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'DIFC',
    linkedinUrl: 'https://www.linkedin.com/in/arif-amiri',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Saeed Al Gergawi',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Dubai Chamber',
    linkedinUrl: 'https://www.linkedin.com/in/saeedalgergawi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ammar Al Malik',
    country: 'United Arab Emirates',
    lane: 'Ecosystem',
    organisation: 'Dubai Internet City',
    linkedinUrl: 'https://www.linkedin.com/in/ammaralmalik',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Noor Sweid',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'Global Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/noor-sweid',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Fadi Ghandour',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'Wamda Capital; Aramex founder',
    linkedinUrl: 'https://www.linkedin.com/in/fadi-ghandour-52353b',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Dany Farha',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'BECO Capital',
    linkedinUrl: 'https://www.linkedin.com/in/danyfarha',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Amir Farha',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'COTU Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/amirfarha',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Walid Hanna',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'MEVP',
    linkedinUrl: 'https://www.linkedin.com/in/walid-s-hanna',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mahmoud Adi',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'Shorooq',
    linkedinUrl: 'https://www.linkedin.com/in/m-adi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Shane Shin',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'Shorooq',
    linkedinUrl: 'https://www.linkedin.com/in/shaneykshin',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Sonia Weymuller',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'VentureSouq',
    linkedinUrl: 'https://www.linkedin.com/in/soniaweymuller',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ibrahim Ajami',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'Mubadala Capital',
    linkedinUrl: 'https://www.linkedin.com/in/ibrahim-ajami-17925456',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Huda Al-Lawati',
    country: 'United Arab Emirates',
    lane: 'Investor',
    organisation: 'Aliph Capital',
    linkedinUrl: 'https://www.linkedin.com/in/huda-al-lawati-62051a5',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Philip Bahoshy',
    country: 'United Arab Emirates',
    lane: 'Media & Research',
    organisation: 'MAGNiTT',
    linkedinUrl: 'https://www.linkedin.com/in/philipbahoshy',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Mudassir Sheikha',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'Careem',
    linkedinUrl: 'https://www.linkedin.com/in/mudassirsheikha',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Ronaldo Mouchawar',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'Souq.com; Amazon',
    linkedinUrl: 'https://www.linkedin.com/in/ronaldomouchawar',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hosam Arab',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'Tabby',
    linkedinUrl: 'https://www.linkedin.com/in/hosam',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Michael Lahyani',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'Property Finder',
    linkedinUrl: 'https://www.linkedin.com/in/michael-lahyani-25827b4',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Faisal Toukan',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'Ziina',
    linkedinUrl: 'https://www.linkedin.com/in/faisal-toukan-64865064',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ola Doudin',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'BitOasis',
    linkedinUrl: 'https://www.linkedin.com/in/ola-doudin-5a026511',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Elie Habib',
    country: 'United Arab Emirates',
    lane: 'Founder',
    organisation: 'Anghami',
    linkedinUrl: 'https://www.linkedin.com/in/eliashabib',
    priority: false,
    arabicOrBilingual: false,
  },

  // Qatar
  {
    name: 'Sheikh Ali bin Alwaleed Al-Thani',
    country: 'Qatar',
    lane: 'Policy',
    organisation: 'Invest Qatar',
    linkedinUrl: 'https://www.linkedin.com/in/ali-al-thani-794879196',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Rama Chakaki',
    country: 'Qatar',
    lane: 'Ecosystem',
    organisation: 'QSTP',
    linkedinUrl: 'https://www.linkedin.com/in/rchakaki',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hayfa Al-Abdulla',
    country: 'Qatar',
    lane: 'Ecosystem',
    organisation: 'QSTP',
    linkedinUrl: 'https://www.linkedin.com/in/haifaa',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mansoor Al-Khater',
    country: 'Qatar',
    lane: 'Ecosystem',
    organisation: 'Qatar Financial Centre',
    linkedinUrl: 'https://www.linkedin.com/in/mansooralkhater',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Huzayfa Patel',
    country: 'Qatar',
    lane: 'Ecosystem',
    organisation: 'QFC Digital Assets Lab',
    linkedinUrl: 'https://www.linkedin.com/in/huzayfa-patel',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Michael Lints',
    country: 'Qatar',
    lane: 'Investor',
    organisation: 'Golden Gate Ventures MENA',
    linkedinUrl: 'https://www.linkedin.com/in/mhlints',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Alexander Wiedmer',
    country: 'Qatar',
    lane: 'Investor',
    organisation: 'Rasmal Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/alexwiedmer13061968',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Soumaya Ben Beya Dridje',
    country: 'Qatar',
    lane: 'Investor',
    organisation: 'Rasmal Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/soumaya-ben-beya-dridje-25574466',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hamad Mubarak Al-Hajri',
    country: 'Qatar',
    lane: 'Founder',
    organisation: 'Snoonu; GrowthX',
    linkedinUrl: 'https://www.linkedin.com/in/hamadmubarkalhajri',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Nayef Al-Ibrahim',
    country: 'Qatar',
    lane: 'Founder',
    organisation: 'Ibtechar',
    linkedinUrl: 'https://www.linkedin.com/in/nayef-al-ibrahim-070a5916',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Steve Mackie',
    country: 'Qatar',
    lane: 'Media & Research',
    organisation: 'Business Start Up Qatar',
    linkedinUrl: 'https://www.linkedin.com/in/stevemackiesolutionsfour',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Dr Hanan El Basha',
    country: 'Qatar',
    lane: 'Ecosystem',
    organisation: 'The Business Doctor',
    linkedinUrl: 'https://www.linkedin.com/in/drhananelbasha',
    priority: false,
    arabicOrBilingual: false,
  },

  // Bahrain
  {
    name: 'Maha Mofeez',
    country: 'Bahrain',
    lane: 'Ecosystem',
    organisation: 'Tamkeen',
    linkedinUrl: 'https://www.linkedin.com/in/maha-mofeez-40291525',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Dalal Buhejji',
    country: 'Bahrain',
    lane: 'Policy',
    organisation: 'Bahrain EDB',
    linkedinUrl: 'https://www.linkedin.com/in/dbuhejji',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Bader Sater',
    country: 'Bahrain',
    lane: 'Ecosystem',
    organisation: 'Bahrain FinTech Bay',
    linkedinUrl: 'https://www.linkedin.com/in/badersater',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Latifa Mohamed Jabbar',
    country: 'Bahrain',
    lane: 'Investor',
    organisation: 'Hope Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/latifa-mohammed',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Areije Al Shakar',
    country: 'Bahrain',
    lane: 'Investor',
    organisation: 'BeVentures',
    linkedinUrl: 'https://www.linkedin.com/in/areije',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hasan Haider',
    country: 'Bahrain',
    lane: 'Investor',
    organisation: 'Plus VC',
    linkedinUrl: 'https://www.linkedin.com/in/hasanhaider',
    priority: true,
    arabicOrBilingual: true,
  },
  {
    name: 'Ahmed Al Rawi',
    country: 'Bahrain',
    lane: 'Founder',
    organisation: 'Calo',
    linkedinUrl: 'https://www.linkedin.com/in/rawi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdulla Almoayed',
    country: 'Bahrain',
    lane: 'Founder',
    organisation: 'Tarabut',
    linkedinUrl: 'https://www.linkedin.com/in/aalmoayed',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Nezar Kadhem',
    country: 'Bahrain',
    lane: 'Founder',
    organisation: 'Eat App',
    linkedinUrl: 'https://www.linkedin.com/in/nezarkadhem',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Wafa Al Obaidat',
    country: 'Bahrain',
    lane: 'Founder',
    organisation: 'PLAYBOOK',
    linkedinUrl: 'https://www.linkedin.com/in/wafa-al-obaidat-8a992046',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ali Alalawi',
    country: 'Bahrain',
    lane: 'Founder',
    organisation: 'Unipal',
    linkedinUrl: 'https://www.linkedin.com/in/ali-alalawi',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Fajer Al Pachachi',
    country: 'Bahrain',
    lane: 'Policy',
    organisation: 'Esterad Bank; Bahrain Chamber',
    linkedinUrl: 'https://www.linkedin.com/in/fajer-saleh-al-pachachi-b38ab116',
    priority: false,
    arabicOrBilingual: false,
  },

  // Kuwait
  {
    name: 'Mohammed Jaffar',
    country: 'Kuwait',
    lane: 'Investor',
    organisation: 'Faith Capital; former Talabat CEO',
    linkedinUrl: 'https://www.linkedin.com/in/mohammed-jaffar-01110a71',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdulaziz Al Loughani',
    country: 'Kuwait',
    lane: 'Founder',
    organisation: 'Floward; Faith Capital',
    linkedinUrl: 'https://www.linkedin.com/in/aballoughani',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Hasan Zainal',
    country: 'Kuwait',
    lane: 'Investor',
    organisation: 'Arzan VC',
    linkedinUrl: 'https://www.linkedin.com/in/hasanzainal',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mona Al-Mukhaizeem',
    country: 'Kuwait',
    lane: 'Investor',
    organisation: 'Savour Ventures; Sirdab Lab',
    linkedinUrl: 'https://www.linkedin.com/in/mona-al-mukhaizeem-921aba8',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Nawaf Arhamah',
    country: 'Kuwait',
    lane: 'Investor',
    organisation: 'F3 Capital',
    linkedinUrl: 'https://www.linkedin.com/in/nawafarhamah',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ali Abulhasan',
    country: 'Kuwait',
    lane: 'Founder',
    organisation: 'Tap Payments',
    linkedinUrl: 'https://www.linkedin.com/in/akabulhasan',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Yousef Alhusaini',
    country: 'Kuwait',
    lane: 'Founder',
    organisation: 'Baims',
    linkedinUrl: 'https://www.linkedin.com/in/yalhusaini',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Hashim Behbehani',
    country: 'Kuwait',
    lane: 'Ecosystem',
    organisation: 'CODED; StartupQ8',
    linkedinUrl: 'https://www.linkedin.com/in/hashimkb',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Haya AlMana',
    country: 'Kuwait',
    lane: 'Ecosystem',
    organisation: 'BNK Academy; formerly ZINC',
    linkedinUrl: 'https://www.linkedin.com/in/hayaalmana',
    priority: false,
    arabicOrBilingual: true,
  },
  {
    name: 'Malek Hammoud',
    country: 'Kuwait',
    lane: 'Investor',
    organisation: 'Zain Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/malek-hammoud-cfa-6689545',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Dalal AlRayes',
    country: 'Kuwait',
    lane: 'Founder',
    organisation: 'Spare',
    linkedinUrl: 'https://www.linkedin.com/in/dalalalrayes',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Bader Al-Ghanim',
    country: 'Kuwait',
    lane: 'Ecosystem',
    organisation: 'talabat',
    linkedinUrl: 'https://www.linkedin.com/in/bader-al-ghanim-973a5b17',
    priority: false,
    arabicOrBilingual: false,
  },

  // Oman
  {
    name: 'Talib Al-Rashdi',
    country: 'Oman',
    lane: 'Investor',
    organisation: 'ITHCA Group',
    linkedinUrl: 'https://www.linkedin.com/in/talib-al-rashdi-5214abb8',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Dr Ali Al Shidhani',
    country: 'Oman',
    lane: 'Policy',
    organisation: 'MTCIT',
    linkedinUrl: 'https://www.linkedin.com/in/alialshidhani',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Ali Muqaibal',
    country: 'Oman',
    lane: 'Investor',
    organisation: 'Sharakah',
    linkedinUrl: 'https://www.linkedin.com/in/alimuqaibal',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Abdullah Al-Shaksy',
    country: 'Oman',
    lane: 'Investor',
    organisation: 'Phaze Ventures',
    linkedinUrl: 'https://www.linkedin.com/in/abdullah-al-shaksy',
    priority: true,
    arabicOrBilingual: false,
  },
  {
    name: 'Masoud Al-Rawahi',
    country: 'Oman',
    lane: 'Investor',
    organisation: 'Phaze Ventures; PhazeRo',
    linkedinUrl: 'https://www.linkedin.com/in/masoud-al-rawahi-15bb0714',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Adnan Alshuaili',
    country: 'Oman',
    lane: 'Founder',
    organisation: 'eMushrif',
    linkedinUrl: 'https://www.linkedin.com/in/adnan-alshuaili-470413136',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Majid AlAmri',
    country: 'Oman',
    lane: 'Founder',
    organisation: 'Thawani Pay',
    linkedinUrl: 'https://www.linkedin.com/in/majid-alamri-0144271a9',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Talal Hasan',
    country: 'Oman',
    lane: 'Founder',
    organisation: '44.01',
    linkedinUrl: 'https://www.linkedin.com/in/talal-hasan',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Harith Maqbali',
    country: 'Oman',
    lane: 'Founder',
    organisation: 'OTaxi',
    linkedinUrl: 'https://www.linkedin.com/in/harith-maqbali-85456365',
    priority: false,
    arabicOrBilingual: false,
  },
  {
    name: 'Mohammed Al-Tamami',
    country: 'Oman',
    lane: 'Media & Research',
    organisation: 'Mamun',
    linkedinUrl: 'https://www.linkedin.com/in/mohamed-tamami',
    priority: false,
    arabicOrBilingual: true,
  },
];
